[package]
name = "fclip"
version = "3.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
arboard = "3.2"
clap = { version = "4.4", features = ["derive"] }
ignore = "0.4"
glob = "0.3"
serde_json = "1.0" 
rayon = "1.8"
indicatif = "0.17"